version: 2
updates:
  # Dependencies listed in .github/workflows/*.yml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
        interval: "weekly"
    rebase-strategy: "disabled"
